Algoritmo "duracao"
Var
   duracao, horas, resto, minutos, segundos: inteiro


Inicio
      escreva("Digite a duração em segundos: ")
      leia(duracao)
      
      horas <- duracao \ 3600 //barra invertida para ter apenas a parte inteira da divisão
      resto <- duracao % 3600
      
      minutos <- resto \ 60
      segundos <- resto % 60
      
      
      escreva(horas, ":", minutos, ":", segundos)

Fimalgoritmo